
services:
  db:
    image: mongo:noble
    container_name: media-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

networks:
  default:
    name: med

volumes:
  db: